/**
 * File: TaxonomiesParserTest.java
 *
 * Copyright 2012 Dan Brown <dan@likethecolor.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.likethecolor.alchemy.api.parser.json;

import com.likethecolor.alchemy.api.Constants;
import com.likethecolor.alchemy.api.entity.TaxonomyAlchemyEntity;
import com.likethecolor.alchemy.api.entity.Response;
import org.junit.Test;

import java.util.Iterator;

import static junit.framework.Assert.assertFalse;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

public class TaxonomiesParserTest {
  private static final String LANGUAGE = "english";
  private static final String STATUS_STRING = "OK";
  private static final String TEXT = "this is some text";
  private static final String USAGE = "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html";
  private static final String URL = "http://www.bartleby.com/124/pres32.html";

  private static final boolean ENTITY0_CONFIDENCE = true;
  private static final String ENTITY0_LABEL = "Slavery";
  private static final Double ENTITY0_SCORE = 0.938707D;

  private static final boolean ENTITY1_CONFIDENCE = false;
  private static final String ENTITY1_LABEL = "Oath_of_office";
  private static final Double ENTITY1_SCORE = 0.935298D;

  private static final boolean ENTITY2_CONFIDENCE = true;
  private static final String ENTITY2_LABEL = "Inauguration";
  private static final Double ENTITY2_SCORE = 0.876062D;

  @Test
  public void testParse() {
    final TaxonomiesParser parser = new TaxonomiesParser();
    final Response<TaxonomyAlchemyEntity> response = parser.parse(getJsonString());

    assertEquals(3, response.size());

    TaxonomyAlchemyEntity entity;
    final Iterator<TaxonomyAlchemyEntity> iter = response.iterator();
    entity = iter.next();
    assertEquals(ENTITY0_CONFIDENCE, entity.isConfident());
    assertEquals(ENTITY0_LABEL, entity.getLabel());
    assertEquals(ENTITY0_SCORE, entity.getScore());

    entity = iter.next();
    assertEquals(ENTITY1_CONFIDENCE, entity.isConfident());
    assertEquals(ENTITY1_LABEL, entity.getLabel());
    assertEquals(ENTITY1_SCORE, entity.getScore());

    entity = iter.next();
    assertEquals(ENTITY2_CONFIDENCE, entity.isConfident());
    assertEquals(ENTITY2_LABEL, entity.getLabel());
    assertEquals(ENTITY2_SCORE, entity.getScore());
  }

  @Test
  public void testParse_NoConfidence() {
    final TaxonomiesParser parser = new TaxonomiesParser();
    final Response<TaxonomyAlchemyEntity> response = parser.parse(getJsonString_NoConfidence());

    assertEquals(1, response.size());

    TaxonomyAlchemyEntity entity;
    final Iterator<TaxonomyAlchemyEntity> iter = response.iterator();
    entity = iter.next();
    assertNull(entity.isConfident());
    assertEquals(ENTITY0_LABEL, entity.getLabel());
    assertEquals(ENTITY0_SCORE, entity.getScore());
  }

  @Test
  public void testParse_NoLabel() {
    final TaxonomiesParser parser = new TaxonomiesParser();
    final Response<TaxonomyAlchemyEntity> response = parser.parse(getJsonString_NoLabel());

    assertEquals(1, response.size());

    TaxonomyAlchemyEntity entity;
    final Iterator<TaxonomyAlchemyEntity> iter = response.iterator();
    entity = iter.next();
    assertEquals(ENTITY0_CONFIDENCE, entity.isConfident());
    assertNull(entity.getLabel());
    assertEquals(ENTITY0_SCORE, entity.getScore());
  }

  @Test
  public void testParse_NoScore() {
    final TaxonomiesParser parser = new TaxonomiesParser();
    final Response<TaxonomyAlchemyEntity> response = parser.parse(getJsonString_NoScore());

    assertEquals(1, response.size());

    TaxonomyAlchemyEntity entity;
    final Iterator<TaxonomyAlchemyEntity> iter = response.iterator();
    entity = iter.next();
    assertEquals(ENTITY0_CONFIDENCE, entity.isConfident());
    assertEquals(ENTITY0_LABEL, entity.getLabel());
    assertEquals(Constants.DEFAULT_SCORE, entity.getScore());
  }

  @Test
  public void testParse_NoTaxonomies() {
    final TaxonomiesParser parser = new TaxonomiesParser();
    final Response<TaxonomyAlchemyEntity> response = parser.parse(getJsonString_NoTaxonomies());

    assertEquals(0, response.size());
  }

  @Test
  public void testParse_NullEmptyJsonString() {
    final TaxonomyParser parser = new TaxonomyParser();
    Response<TaxonomyAlchemyEntity> response = parser.parse(null);

    assertEquals(0, response.size());

    response = parser.parse("");

    assertEquals(0, response.size());

    response = parser.parse("\t  \r\n");

    assertEquals(0, response.size());
  }

  /**
   * Has confidence, label, and score.
   */
  private String getJsonString() {
    return "{\"" + JSONConstants.RESULTS_STATUS + "\":\"" + STATUS_STRING + "\"," +
           "\"" + JSONConstants.RESULTS_USAGE + "\": \"" + USAGE + "\"," +
           "\"" + JSONConstants.RESULTS_URL + "\": \"" + URL + "\"," +
           "\"" + JSONConstants.RESULTS_LANGUAGE + "\": \"" + LANGUAGE + "\"," +
           "\"" + JSONConstants.RESULTS_TEXT + "\": \"" + TEXT + "\"," +
           "\"" + JSONConstants.TAXONOMY_KEY + "\": [" +
           "{\"" + JSONConstants.TAXONOMY_CONFIDENCE_KEY + "\":" + ENTITY0_CONFIDENCE + ",\"" + JSONConstants.TAXONOMY_LABEL_KEY + "\": \"" + ENTITY0_LABEL + "\",\"" + JSONConstants.TAXONOMY_SCORE_KEY + "\": " + ENTITY0_SCORE + "}," +
           "{\"" + JSONConstants.TAXONOMY_CONFIDENCE_KEY + "\":" + ENTITY1_CONFIDENCE + ",\"" + JSONConstants.TAXONOMY_LABEL_KEY + "\": \"" + ENTITY1_LABEL + "\",\"" + JSONConstants.TAXONOMY_SCORE_KEY + "\": " + ENTITY1_SCORE + "}," +
           "{\"" + JSONConstants.TAXONOMY_CONFIDENCE_KEY + "\":" + ENTITY2_CONFIDENCE + ",\"" + JSONConstants.TAXONOMY_LABEL_KEY + "\": \"" + ENTITY2_LABEL + "\",\"" + JSONConstants.TAXONOMY_SCORE_KEY + "\": " + ENTITY2_SCORE + "}]}";
  }

  /**
   * JSON with 1 taxonomy, no label.
   */
  private String getJsonString_NoLabel() {
    return "{\"" + JSONConstants.RESULTS_STATUS + "\":\"" + STATUS_STRING + "\"," +
           "\"" + JSONConstants.RESULTS_USAGE + "\": \"" + USAGE + "\"," +
           "\"" + JSONConstants.RESULTS_URL + "\": \"" + URL + "\"," +
           "\"" + JSONConstants.RESULTS_LANGUAGE + "\": \"" + LANGUAGE + "\"," +
           "\"" + JSONConstants.RESULTS_TEXT + "\": \"" + TEXT + "\"," +
           "\"" + JSONConstants.TAXONOMY_KEY + "\": [" +
           "{\"" + JSONConstants.TAXONOMY_CONFIDENCE_KEY + "\":" + ENTITY0_CONFIDENCE + ",\"" + JSONConstants.TAXONOMY_SCORE_KEY + "\": " + ENTITY0_SCORE + "}" +
           "]}";
  }

  /**
   * JSON with 1 taxonomy, no score.
   */
  private String getJsonString_NoScore() {
    return "{\"" + JSONConstants.RESULTS_STATUS + "\":\"" + STATUS_STRING + "\"," +
           "\"" + JSONConstants.RESULTS_USAGE + "\": \"" + USAGE + "\"," +
           "\"" + JSONConstants.RESULTS_URL + "\": \"" + URL + "\"," +
           "\"" + JSONConstants.RESULTS_LANGUAGE + "\": \"" + LANGUAGE + "\"," +
           "\"" + JSONConstants.RESULTS_TEXT + "\": \"" + TEXT + "\"," +
           "\"" + JSONConstants.TAXONOMY_KEY + "\": [" +
           "{\"" + JSONConstants.TAXONOMY_CONFIDENCE_KEY + "\":" + ENTITY0_CONFIDENCE + ",\"" + JSONConstants.TAXONOMY_LABEL_KEY + "\": \"" + ENTITY0_LABEL + "\"}" +
           "]}";
  }

  /**
   * Has 1 taxonomy - no confidence.
   */
  private String getJsonString_NoConfidence() {
    return "{\"" + JSONConstants.RESULTS_STATUS + "\":\"" + STATUS_STRING + "\"," +
           "\"" + JSONConstants.RESULTS_USAGE + "\": \"" + USAGE + "\"," +
           "\"" + JSONConstants.RESULTS_URL + "\": \"" + URL + "\"," +
           "\"" + JSONConstants.RESULTS_LANGUAGE + "\": \"" + LANGUAGE + "\"," +
           "\"" + JSONConstants.RESULTS_TEXT + "\": \"" + TEXT + "\"," +
           "\"" + JSONConstants.TAXONOMY_KEY + "\": [" +
           "{\"" + JSONConstants.TAXONOMY_LABEL_KEY + "\": \"" + ENTITY0_LABEL + "\",\"" + JSONConstants.TAXONOMY_SCORE_KEY + "\": " + ENTITY0_SCORE + "}]}";
  }

  /**
   * JSON with 0 taxonomies
   */
  private String getJsonString_NoTaxonomies() {
    return "{\"" + JSONConstants.RESULTS_STATUS + "\":\"" + STATUS_STRING + "\"," +
           "\"" + JSONConstants.RESULTS_USAGE + "\": \"" + USAGE + "\"," +
           "\"" + JSONConstants.RESULTS_URL + "\": \"" + URL + "\"," +
           "\"" + JSONConstants.RESULTS_LANGUAGE + "\": \"" + LANGUAGE + "\"," +
           "\"" + JSONConstants.RESULTS_TEXT + "\": \"" + TEXT + "\"}";
  }
}
